url: http://theoffercast.com/
baseurl: http://theoffercast.com/

# Site settings
title: The Offer
email: contact@theoffercast.com
description: "The Offer is a podcast of stories. Stories which are entirely true, in that they have never been edited... or written down. Each week, a group of people meet and improvise a story. Usually stays into comedy, which comes from the surprise of the adventure. Every week we have a conversation, from which we improvise a wacky tale just for your ears. Monthly musical episodes, genre stories, and more. "
disqus: theofferpodcast # get it on https://disqus.com/admin/

# Team names, titles and social links
people:
- name: Cesar Goz
  pic: 1
  position: Co-Producer | Co-Host
  social:
  #  - title: twitter
  #    url: #
    - title: facebook
      url: https://www.facebook.com/CesarDGozurreta
    - title: linkedin
      url: https://www.linkedin.com/in/cesar-gozurreta/

- name: Paul Deichmann
  pic: 2
  position: Co-Producer | Co-Host
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/OfferPod
  - title: linkedin
    url: http://www.linkedin.com/company/42371723
# - title: stack-overflow
#   url: http://stackoverflow.com/questions/tagged/jekyll
# - title: bitbucket 
#   url: http://bitbucket.org/jekyll
# - title: github
#   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

#Plugins
plugins:
  - jekyll-seo-tag

#<------------------------Jekyll spotify---------------------------------------->
gems: [jekyll-spotify]



#<----------------------- Guests --------------------------->

guests:
- name: Matt Lovelace
  pic: mat
  position: Danklord
  social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: https://www.facebook.com/CesarDGozurreta
  #  - title: linkedin
  #    url: https://www.linkedin.com/in/cesar-gozurreta/
- name: Sonia Zhang
  pic: sonia
  position: ice-cream collector
  social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: https://www.facebook.com/CesarDGozurreta
    - title: linkedin
      url: https://www.linkedin.com/in/qianqing-zhang-644b28a9/
- name: Ben Browder Thompson
  pic: browder
  position: Creative who sets off metal detectors
  social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: https://www.facebook.com/CesarDGozurreta
  #  - title: linkedin
  #    url: https://www.linkedin.com/in/qianqing-zhang-644b28a9/
- name: William Taylor Hood XIII
  pic: will
  position: Keyboard Killer
  social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: https://www.facebook.com/CesarDGozurreta
  #  - title: linkedin
  #    url: https://www.linkedin.com/in/qianqing-zhang-644b28a9/
- name: Lilian Shen
  pic: lilian
  position: Artistic Director of Zmack
  social:
    - title: facebook
      url: https://www.facebook.com/zmackcomedy/
    - title: linkedin
      url: https://www.linkedin.com/company/zmack/about/
  #  - title: twitter
  #    url: #
  #  - title: wbesite
  #    url: https://www.zmack.net/
  #  - title: wechat
  #    url: zmackshanghai
- name: Eddie Jordan III
  pic: etriiiip
  position: Call me Etriiip
  social:
    - title: facebook
      url: https://www.facebook.com/eddie.i.jordan
    - title: linkedin
      url: https://www.linkedin.com/in/eddie-jordan-iii-etriiip-41899077/
  #  - title: twitter
  #    url: #
  #  - title: wbesite
  #    url: https://www.zmack.net/
  #  - title: instagram
  #    url: etriiip

