url: http://theoffercast.com/
baseurl: http://theoffercast.com/

# Site settings
title: The Offer
email: contact@theoffercast.com
description: "The best improvised comedy podcast in the world."
disqus: theofferpodcast # get it on https://disqus.com/admin/

# Team names, titles and social links
people:
- name: Caesar Goz
  pic: 3
  position: Producer | Host
  social:
  #  - title: twitter
  #    url: #
    - title: facebook
      url: https://www.facebook.com/CesarDGozurreta
    - title: linkedin
      url: https://www.linkedin.com/in/cesar-gozurreta/

- name: Victoria Bender
  pic: victoria
  position: Actor | Improviser | Costumer
  social:
    - title: facebook
      url: https://www.facebook.com/mindbendertrivia/
    - title: linkedin
      url: https://www.linkedin.com/in/vjbender/
    - title: instagram
      url: https://www.instagram.com/bendini_creative

- name: Paul Deichmann
  pic: 2
  position: Producer | Host
  social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: #
  #  - title: linkedin
  #    url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/OfferPod
  - title: linkedin
    url: http://www.linkedin.com/company/42371723
  - title: instagram
    url: https://www.instagram.com/theoffercast/
  - title: facebook
    url: https://www.facebook.com/theoffercast
  - title: youtube
    url: https://www.youtube.com/channel/UC_dEFfqsg_dCzokLno6_bgw
  - title: discord
    url: https://discord.gg/Q6ZpkecX

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

#Plugins
plugins:
  - jekyll-seo-tag

#<------------------------Jekyll spotify---------------------------------------->
gems: [jekyll-spotify]

#<------------------------playlists---------------------------------------->
playlists:
  uno
  dos
  tres
  cuatro

#<----------------------- Guests --------------------------->

guests:
- name: Eddie Jordan III
  pic: etriiiip
  position: Call me Etriiip
  social:
    - title: facebook
      url: https://www.facebook.com/eddie.i.jordan
    - title: linkedin
      url: https://www.linkedin.com/in/eddie-jordan-iii-etriiip-41899077/
  #  - title: twitter
  #    url: #
  #  - title: wbesite
  #    url: https://www.zmack.net/
    - title: instagram
      url: etriiip
- name: Julien Bertrand 
  pic: julien
  position: Actor | Writer | Director 
  social:
    - title: facebook
      url: https://www.facebook.com/julienactor/
    - title: linkedin
      url: https://www.linkedin.com/in/julien-bertrand-2b884516/
- name: Curt Mabry
  pic: curt
  position: Working Improviser
  social:
    - title: facebook
      url: https://www.facebook.com/zmackcomedy/
    - title: linkedin
      url: https://www.linkedin.com/in/curtmabryimproviser/

- name: Iris Park
  pic: iris
  position: Actor | Improviser | Wannabe Polyglot
  social:
    - title: facebook
      url: https://web.facebook.com/Irisia/
    - title: instagram
      url:  https://www.instagram.com/irisiapark/ 

- name: Darryl Charles
  pic: darryl
  position: Comedian | Improviser | Comedy Writer
  social:
    - title: globe
      url: http://www.darrylcharlescomedy.com/home.html


- name: Sonia Zhang
  
  pic: sonia
  position: ice-cream collector
  social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: https://www.facebook.com/CesarDGozurreta
    - title: linkedin
      url: https://www.linkedin.com/in/qianqing-zhang-644b28a9/
#- name: Victoria Bender
#  pic: victoria
#  position: Actor | Improviser | Costumer
#  social:
#    - title: facebook
#      url: https://www.facebook.com/mindbendertrivia/
#    - title: linkedin
#      url: https://www.linkedin.com/in/vjbender/
#    - title: instagram
#      url: https://www.instagram.com/bendini_creative
#  #  - title: blobe
#  #    url: https://www.zmack.net/
#  #  - title: wechat
#  #    url: zmackshanghai
#    - title: wechat
#      url: ZmackShanghai
- name: Tony Perea 
  pic: tony
  position: Actor | Writer | Musician.
  social:
    - title: facebook
      url: https://www.facebook.com/antonio.perea.73
    
#    - title: instagram
#      url: @afpafpafp
- name: Andi Fei
  pic: andi
  position: Improviser | Dog Trainer | Entrepreneur
  social:
    - title: facebook
      url: https://www.facebook.com/afpafpafp
    - title: youtube
      url: https://www.youtube.com/channel/UCzsLUx2rVWEXNjFW4WnVUsg
    - title: instagram
      url: https://www.instagram.com/afpafpafp/
- name: Ben Browder Thompson
  pic: browder
  position: Creative who sets off metal detectors
  social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: https://www.facebook.com/CesarDGozurreta
  #  - title: linkedin
  #    url: https://www.linkedin.com/in/qianqing-zhang-644b28a9/
- name: Matt Lovelace
  pic: mat
  position: Danklord
  social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: https://www.facebook.com/CesarDGozurreta
  #  - title: linkedin
  #    url: https://www.linkedin.com/in/cesar-gozurreta/
- name: Gary Yarbrough
  pic: gary
  position: Organic Coconuts
  social:
    - title: facebook
      url: https://www.facebook.com/garysy
    - title: linkedin
      url: https://www.linkedin.com/in/garysy
    - title: twitter
      url: hhtps://www.twitter.com/garysy
  #  - title: wbesite
  #    url: https://www.zmack.net/
  #  - title: wechat
  #    url: zmackshanghai
#    - title: instagram
#      url: Zmackbkk
#    - title: wechat
#      url: ZmackShanghai
- name: LlauraH Improviser
  pic: llaura
  position: Improviser | Director | Psychologist
  social:
    - title: facebook
      url: https://www.facebook.com/llaura.himproviser
    - title: instagram
      url: https://www.instagram.com/Llaurah_improviser
- name: William Taylor Hood XIII
  pic: will
  position: Keyboard Killer
  social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: https://www.facebook.com/CesarDGozurreta
  #  - title: linkedin
  #    url: https://www.linkedin.com/in/qianqing-zhang-644b28a9/
- name: Lilian Shen
  pic: lilian
  position: Artistic Director of Zmack
  social:
    - title: facebook
      url: https://www.facebook.com/zmackcomedy/
    - title: linkedin
      url: https://www.linkedin.com/company/zmack/about/
    - title: globe
      url: https://www.zmack.net/
    - title: instagram
      url: https://www.instagram.com/Zmackbkk
  #  - title: wechat
  #    url: zmackshanghai
#    - title: wechat
#      url: ZmackShanghai

