url: http://theoffercast.com/
baseurl: http://theoffercast.com/

# Site settings
title: The Offer Improvised Original Stories Podcast
email: contact@theoffercast.com
description: "The Offer is an improvised stories podcast. Each week, our hosts, Paul and Cesar, create a completely original long-form story with an amazing guest. Expect comedy, authenticy and very high-level improv."
disqus: theofferpodcast # get it on https://disqus.com/admin/

# Team names, titles and social links
people:
- name: Caesar Goz
  pic: 1
  position: Co-Producer | Co-Host
  social:
  #  - title: twitter
  #    url: #
    - title: facebook
      url: https://www.facebook.com/CesarDGozurreta
    - title: linkedin
      url: https://www.linkedin.com/in/cesar-gozurreta/

- name: Paul Deichmann
  pic: 2
  position: Co-Producer | Co-Host
  social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: #
  #  - title: linkedin
  #    url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/OfferPod
  - title: linkedin
    url: http://www.linkedin.com/company/42371723
# - title: stack-overflow
#   url: http://stackoverflow.com/questions/tagged/jekyll
# - title: bitbucket 
#   url: http://bitbucket.org/jekyll
# - title: github
#   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

#Plugins
plugins:
  - jekyll-seo-tag

#<------------------------Jekyll spotify---------------------------------------->
gems: [jekyll-spotify]

#<------------------------playlists---------------------------------------->
playlists:
  uno
  dos
  tres
  cuatro

#<----------------------- Guests --------------------------->

guests:
- name: Eddie Jordan III
  pic: etriiiip
  position: Call me Etriiip
  social:
    - title: facebook
      url: https://www.facebook.com/eddie.i.jordan
    - title: linkedin
      url: https://www.linkedin.com/in/eddie-jordan-iii-etriiip-41899077/
  #  - title: twitter
  #    url: #
  #  - title: wbesite
  #    url: https://www.zmack.net/
  #  - title: instagram
  #    url: etriiip
- name: Julien Bertrand 
  pic: julien
  position: Actor | Writer | Director 
  social:
    - title: facebook
      url: https://www.facebook.com/julienactor/
    - title: linkedin
      url: https://www.linkedin.com/in/julien-bertrand-2b884516/
- name: Curt Mabry
  pic: curt
  position: Working Improviser
  social:
    - title: facebook
      url: https://www.facebook.com/zmackcomedy/
    - title: linkedin
      url: https://www.linkedin.com/in/curtmabryimproviser/
- name: Sonia Zhang
  pic: sonia
  position: ice-cream collector
  social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: https://www.facebook.com/CesarDGozurreta
    - title: linkedin
      url: https://www.linkedin.com/in/qianqing-zhang-644b28a9/
- name: Victoria Bender
  pic: victoria
  position: Actor | Improviser | Costumer
  social:
    - title: facebook
      url: https://www.facebook.com/mindbendertrivia/
    - title: linkedin
      url: https://www.linkedin.com/in/vjbender/
  #  - title: instagram
  #    url: @bendini_creative
  #  - title: wbesite
  #    url: https://www.zmack.net/
  #  - title: wechat
  #    url: zmackshanghai
#    - title: wechat
#      url: ZmackShanghai
- name: Ben Browder Thompson
  pic: browder
  position: Creative who sets off metal detectors
  social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: https://www.facebook.com/CesarDGozurreta
  #  - title: linkedin
  #    url: https://www.linkedin.com/in/qianqing-zhang-644b28a9/
- name: Matt Lovelace
  pic: mat
  position: Danklord
  social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: https://www.facebook.com/CesarDGozurreta
  #  - title: linkedin
  #    url: https://www.linkedin.com/in/cesar-gozurreta/
- name: Gary Yarbrough
  pic: gary
  position: Organic Coconuts
  social:
    - title: facebook
      url: https://www.facebook.com/garysy
    - title: linkedin
      url: https://www.linkedin.com/in/garysy
    - title: twitter
      url: hhtps://www.twitter.com/garysy
  #  - title: wbesite
  #    url: https://www.zmack.net/
  #  - title: wechat
  #    url: zmackshanghai
#    - title: instagram
#      url: Zmackbkk
#    - title: wechat
#      url: ZmackShanghai
- name: William Taylor Hood XIII
  pic: will
  position: Keyboard Killer
  social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: https://www.facebook.com/CesarDGozurreta
  #  - title: linkedin
  #    url: https://www.linkedin.com/in/qianqing-zhang-644b28a9/
- name: Lilian Shen
  pic: lilian
  position: Artistic Director of Zmack
  social:
    - title: facebook
      url: https://www.facebook.com/zmackcomedy/
    - title: linkedin
      url: https://www.linkedin.com/company/zmack/about/
  #  - title: twitter
  #    url: #
  #  - title: wbesite
  #    url: https://www.zmack.net/
  #  - title: wechat
  #    url: zmackshanghai
#    - title: instagram
#      url: Zmackbkk
#    - title: wechat
#      url: ZmackShanghai

