url: https://tabrisarg.github.io/theofferpodcast/
baseurl: /theofferpodcast/

# Site settings
title: The Offer
email: the.offer.podcast@gmail.com.com
description: "The Offer is a podcast of stories. Stories which are entirely true, in that they have never been edited... or written down. Each week, a group of people meet and improvise a story. Usually stays into comedy, which comes from the surprise of the adventure. Every week we have a conversation, from which we improvise a wacky tale just for your ears. Monthly musical episodes, genre stories, and more. "


# Team names, titles and social links
people:
- name: Cesar Goz
  pic: 1
  position: Co-Producer | Co-Host
  social:
  #  - title: twitter
  #    url: #
    - title: facebook
      url: https://www.facebook.com/CesarDGozurreta
    - title: linkedin
      url: https://www.linkedin.com/in/cesar-gozurreta/

- name: Paul Deichmann
  pic: 2
  position: Co-Producer | Co-Host
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/OfferPod
#  - title: facebook
#    url:
# - title: stack-overflow
#   url: http://stackoverflow.com/questions/tagged/jekyll
# - title: bitbucket 
#   url: http://bitbucket.org/jekyll
# - title: github
#   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

#Plugins
plugins:
  - jekyll-seo-tag

#<------------------------Jekyll spotify---------------------------------------->
gems: [jekyll-spotify]